setopt ALWAYSTOEND
setopt NOTIFY
setopt AUTOLIST
setopt AUTOCD
setopt PRINTEIGHTBIT
setopt INTERACTIVECOMMENTS

setopt APPENDHISTORY
setopt INCAPPENDHISTORY
setopt HISTIGNORE_DUPS
setopt HISTIGNORESPACE
setopt HISTREDUCEBLANKS
setopt HISTVERIFY

DIRSTACKSIZE=24
setopt autopushd pushdminus
